image_width: 1600
image_height: 1200
camera_name: arducam
camera_matrix:
  rows: 3
  cols: 3
  data: [912.46123,   0.     , 844.67016,
           0.     , 909.96719, 650.42199,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.032108, -0.030853, -0.000478, -0.004221, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [918.6568 ,   0.     , 836.22406,   0.     ,
           0.     , 919.91254, 649.58231,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
