scan_filter_chain:
   - name: angle
     type: laser_filters/LaserScanAngularBoundsFilterInPlace
     params:
       lower_angle: -1.25
       upper_angle: -0.225
   - name: otherAngle
     type: laser_filters/LaserScanAngularBoundsFilter
     params:
       lower_angle: -3.14
       upper_angle: 3.1